## Loading data and Creating dataframe

In [1]:
url = "https://data.humdata.org/dataset/wfp-food-prices-for-india/resource/3b1ff071-6b01-4998-aa62-2f3efb5d4888/download/wfp_food_prices_ind.csv"

In [2]:
# libraries imports
import os
import requests
import pandas as pd
import io

In [3]:
# loading data
headers = {"User-Agent": "Mozilla/5.0"}
response = requests.get(url, headers=headers)
print(response.status_code)

200

In [4]:
df_foodprices = pd.read_csv(io.StringIO(response.text))
df_foodprices.head()

,date,admin1,admin2,market,market_id,latitude,longitude,category,commodity,commodity_id,unit,priceflag,pricetype,currency,price,usdprice
0,1994-01-15,Delhi,Delhi,Delhi,934,28.67,77.22,cereals and tubers,Rice,52,KG,actual,Retail,INR,8.0,0.26
1,1994-01-15,Delhi,Delhi,Delhi,934,28.67,77.22,cereals and tubers,Wheat,84,KG,actual,Retail,INR,5.0,0.16
2,1994-01-15,Delhi,Delhi,Delhi,934,28.67,77.22,miscellaneous food,Sugar,97,KG,actual,Retail,INR,13.5,0.43
3,1994-01-15,Delhi,Delhi,Delhi,934,28.67,77.22,oil and fats,Oil (mustard),228,KG,actual,Retail,INR,31.0,0.99
4,1994-01-15,Gujarat,Ahmadabad,Ahmedabad,923,23.03,72.62,cereals and tubers,Rice,52,KG,actual,Retail,INR,6.8,0.22

## Explorations

In [5]:
df_foodprices.shape

(206167, 16)

In [6]:
print("columns: ", df_foodprices.columns)
print()
print("states covered: ", df_foodprices["admin1"].unique())
print()
print("commodities included: ", df_foodprices["commodity"].unique())
print()
print("categories division: ", df_foodprices["category"].unique())
print()
print("Date range: ", df_foodprices['date'].min(), "to", df_foodprices["date"].max())

columns:  Index(['date', 'admin1', 'admin2', 'market', 'market_id', 'latitude',
       'longitude', 'category', 'commodity', 'commodity_id', 'unit',
       'priceflag', 'pricetype', 'currency', 'price', 'usdprice'],
      dtype='str')

states covered:  <StringArray>
[              'Delhi',             'Gujarat',    'Himachal Pradesh',
           'Karnataka',      'Madhya Pradesh',         'Maharashtra',
              'Orissa',           'Telangana',             'Tripura',
         'West Bengal',           'Meghalaya',           'Rajasthan',
          'Tamil Nadu',               'Assam',              'Kerala',
       'Uttar Pradesh',             'Mizoram',               'Bihar',
          'Chandigarh',           'Jharkhand',            'Nagaland',
              'Punjab',         'Uttarakhand',      'Andhra Pradesh',
             'Haryana', 'Andaman and Nicobar',          'Puducherry',
                 'Goa',                   nan,        'Chhattisgarh',
             'Manipur',              'Sikkim']
Length: 32, dtype: str

commodities included:  <StringArray>
[                   'Rice',                   'Wheat',
                   'Sugar',           'Oil (mustard)',
                'Potatoes',               'Chickpeas',
                  'Onions',                    'Milk',
             'Wheat flour',      'Milk (pasteurized)',
          'Salt (iodised)',         'Oil (groundnut)',
              'Oil (palm)',         'Oil (sunflower)',
         'Lentils (masur)',                'Tomatoes',
             'Tea (black)',                 'Lentils',
     'Sugar (jaggery/gur)',        'Ghee (vanaspati)',
         'Lentils (moong)',          'Lentils (urad)',
           'Oil (soybean)',        'Millet (bulrush)',
         'Millet (finger)',                'Semolina',
                 'Sorghum',   'Wheat flour (refined)',
                    'Eggs',             'Ghee (desi)',
    'Chili (red, dry raw)', 'Coriander seeds (whole)',
     'Cumin seeds (whole)',  'Peppers (black, whole)',
       'Turmeric (powder)',                  'Butter',
        'Chickpea (flour)',                 'Bananas',
               'Eggplants',                  'Garlic',
                  'Ginger']
Length: 41, dtype: str

categories division:  <StringArray>
[   'cereals and tubers',    'miscellaneous food',          'oil and fats',
       'pulses and nuts', 'vegetables and fruits',        'milk and dairy',
   'meat, fish and eggs']
Length: 7, dtype: str

Date range:  1994-01-15 to 2026-02-15

In [7]:
url2 = "https://data.humdata.org/dataset/5755ce3e-d7c1-43d1-9261-3572da899321/resource/f30f9c89-bb20-4e44-b4e9-5dc69b74a533/download/hdx_hapi_poverty_rate_ind.csv"

In [8]:
headers1 = {"User-Agent": "Mozilla/5.0"}
response1 = requests.get(url2, headers=headers1)

print(response1.status_code)
print(response1.text[:300])

df_poverty = pd.read_csv(io.StringIO(response1.text))
df_poverty.head(2)

200
location_code,has_hrp,in_gho,provider_admin1_name,admin1_code,admin1_name,admin_level,mpi,headcount_ratio,intensity_of_deprivation,vulnerable_to_poverty,in_severe_poverty,reference_period_start,reference_period_end
IND,False,False,,,,0,0.1217,27.6781,43.9622,18.9196,8.7151,2015-01-01,2016-12-31
IN

,location_code,has_hrp,in_gho,provider_admin1_name,admin1_code,admin1_name,admin_level,mpi,headcount_ratio,intensity_of_deprivation,vulnerable_to_poverty,in_severe_poverty,reference_period_start,reference_period_end
0,IND,False,False,NaN,NaN,NaN,0,0.1217,27.6781,43.9622,18.9196,8.7151,2015-01-01,2016-12-31
1,IND,False,False,NaN,NaN,NaN,0,0.2827,55.0742,51.3271,17.0205,27.7771,2005-01-01,2006-12-31

## Explorations

In [9]:
print("Shape of df: ", df_poverty.shape)
print()
print("columns: ", df_poverty.columns)

Shape of df:  (97, 14)

columns:  Index(['location_code', 'has_hrp', 'in_gho', 'provider_admin1_name',
       'admin1_code', 'admin1_name', 'admin_level', 'mpi', 'headcount_ratio',
       'intensity_of_deprivation', 'vulnerable_to_poverty',
       'in_severe_poverty', 'reference_period_start', 'reference_period_end'],
      dtype='str')

In [10]:
print("states covered: ", df_poverty["provider_admin1_name"].unique())

states covered:  <StringArray>
[                                   nan,
            'Andaman & Nicobar Islands',
                       'Andhra Pradesh',
                    'Arunachal Pradesh',
                                'Assam',
                                'Bihar',
                           'Chandigarh',
                         'Chhattisgarh',
 'Dadra & Nagar Haveli and Daman & Diu',
                                'Delhi',
                                  'Goa',
                              'Gujarat',
                              'Haryana',
                     'Himachal Pradesh',
                      'Jammu & Kashmir',
                            'Jharkhand',
                            'Karnataka',
                               'Kerala',
                               'Ladakh',
                          'Lakshadweep',
                       'Madhya Pradesh',
                          'Maharashtra',
                              'Manipur',
                            'Meghalaya',
                              'Mizoram',
                             'Nagaland',
                               'Odisha',
                           'Puducherry',
                               'Punjab',
                            'Rajasthan',
                               'Sikkim',
                           'Tamil Nadu',
                            'Telangana',
                              'Tripura',
                        'Uttar Pradesh',
                          'Uttarakhand',
                          'West Bengal']
Length: 37, dtype: str

In [11]:
print(df_poverty[df_poverty['provider_admin1_name'].notna()][['provider_admin1_name', 'mpi', 'headcount_ratio', 'in_severe_poverty', 'reference_period_start']].head(10))

         provider_admin1_name     mpi  headcount_ratio  in_severe_poverty  \
3   Andaman & Nicobar Islands  0.0142           3.6708             0.4575
4              Andhra Pradesh  0.2356          49.8836            21.5491
5              Andhra Pradesh  0.0631          15.4135             3.1922
6              Andhra Pradesh  0.0278           7.1138             0.9091
7           Arunachal Pradesh  0.3128          59.9419            32.0036
8           Arunachal Pradesh  0.1076          24.3453             7.5592
9           Arunachal Pradesh  0.0541          13.2061             2.7448
10                      Assam  0.3171          61.6816            32.4914
11                      Assam  0.1615          36.1840            12.1818
12                      Assam  0.0899          21.4105             5.4333

   reference_period_start
3              2019-01-01
4              2005-01-01
5              2015-01-01
6              2019-01-01
7              2005-01-01
8              2015-01-01
9              2019-01-01
10             2005-01-01
11             2015-01-01
12             2019-01-01

In [13]:
# saving these datasets
df_foodprices.to_csv("../data/food_prices.csv", index = False)
df_poverty.to_csv("../data/poverty.csv", index = False)

print("datasets saved as csv")

datasets saved as csv