In [2]:
# imports
import pandas as pd

In [3]:
# loading both csvs
df_foodprices = pd.read_csv("../data/food_prices.csv")
df_poverty = pd.read_csv("../data/poverty.csv")

df_foodprices.head(3)

,date,admin1,admin2,market,market_id,latitude,longitude,category,commodity,commodity_id,unit,priceflag,pricetype,currency,price,usdprice
0,1994-01-15,Delhi,Delhi,Delhi,934,28.67,77.22,cereals and tubers,Rice,52,KG,actual,Retail,INR,8.0,0.26
1,1994-01-15,Delhi,Delhi,Delhi,934,28.67,77.22,cereals and tubers,Wheat,84,KG,actual,Retail,INR,5.0,0.16
2,1994-01-15,Delhi,Delhi,Delhi,934,28.67,77.22,miscellaneous food,Sugar,97,KG,actual,Retail,INR,13.5,0.43

In [4]:
df_poverty.head(3)

,location_code,has_hrp,in_gho,provider_admin1_name,admin1_code,admin1_name,admin_level,mpi,headcount_ratio,intensity_of_deprivation,vulnerable_to_poverty,in_severe_poverty,reference_period_start,reference_period_end
0,IND,False,False,NaN,NaN,NaN,0,0.1217,27.6781,43.9622,18.9196,8.7151,2015-01-01,2016-12-31
1,IND,False,False,NaN,NaN,NaN,0,0.2827,55.0742,51.3271,17.0205,27.7771,2005-01-01,2006-12-31
2,IND,False,False,NaN,NaN,NaN,0,0.0688,16.3928,41.9761,18.6869,4.2454,2019-01-01,2021-12-31

In [5]:
print("shape of food prices data: ", df_foodprices.shape)
print("shape of poverty data: ", df_poverty.shape)

shape of food prices data:  (206167, 16)
shape of poverty data:  (97, 14)

In [6]:
df_poverty.dtypes

location_code                   str
has_hrp                        bool
in_gho                         bool
provider_admin1_name            str
admin1_code                 float64
admin1_name                 float64
admin_level                   int64
mpi                         float64
headcount_ratio             float64
intensity_of_deprivation    float64
vulnerable_to_poverty       float64
in_severe_poverty           float64
reference_period_start          str
reference_period_end            str
dtype: object

In [7]:
df_foodprices.dtypes

date                str
admin1              str
admin2              str
market              str
market_id         int64
latitude        float64
longitude       float64
category            str
commodity           str
commodity_id      int64
unit                str
priceflag           str
pricetype           str
currency            str
price           float64
usdprice        float64
dtype: object

### Cleaning

In [8]:
# dropping irrelavant columns
df_foodprices = df_foodprices.drop(columns=['market_id', 'priceflag', 'currency'])
df_poverty = df_poverty.drop(columns=['location_code', 'has_hrp', 'in_gho', 'admin1_code', 'admin1_name', 'admin_level'])

print("shape of food prices data: ", df_foodprices.shape)
print("shape of poverty data: ", df_poverty.shape)

shape of food prices data:  (206167, 13)
shape of poverty data:  (97, 8)

In [9]:
# missigng values
print(df_foodprices.isna().sum())
print()
print(df_poverty.isna().sum())

date              0
admin1          736
admin2          736
market            0
latitude        736
longitude       736
category          0
commodity         0
commodity_id      0
unit              0
pricetype         0
price             0
usdprice          0
dtype: int64

provider_admin1_name        3
mpi                         0
headcount_ratio             0
intensity_of_deprivation    0
vulnerable_to_poverty       0
in_severe_poverty           0
reference_period_start      0
reference_period_end        0
dtype: int64

In [10]:
df_foodprices = df_foodprices.dropna(subset=['admin1', 'admin2', 'latitude', 'longitude'])
df_poverty = df_poverty.dropna(subset='provider_admin1_name')

print(df_foodprices.shape)
print(df_poverty.shape)

(205431, 13)
(94, 8)

In [11]:
# changing datatypes
df_foodprices['date'] = pd.to_datetime(df_foodprices['date'])

df_poverty['reference_period_start'] = pd.to_datetime(df_poverty['reference_period_start'])
df_poverty['reference_period_end'] = pd.to_datetime(df_poverty['reference_period_end'])

In [12]:
# handling duplicates
df_foodprices = df_foodprices.duplicated().sum()

In [13]:
df_poverty.duplicated().sum()

np.int64(0)

In [15]:
# whitespace check
print(df_foodprices['admin1'].unique()[:5])
print(df_poverty['provider_admin1_name'].unique()[:5])

IndexError: invalid index to scalar variable.

In [16]:
# filtering irrelavant rows
print(df_foodprices['pricetype'].unique())

IndexError: invalid index to scalar variable.

In [17]:
# final check
print("Food prices shape:", df_foodprices.shape)
print("Poverty shape:", df_poverty.shape)
print()
print(df_foodprices.describe())
print()
print(df_poverty.describe())

Food prices shape: ()
Poverty shape: (94, 8)

AttributeError: 'numpy.int64' object has no attribute 'describe'

In [ ]:
# saving cleaned df
df_foodprices.to_csv('../data/food_prices_cleaned.csv', index= False)
df_poverty.to_csv('../data/poverty_cleaned.csv', index=False)

print("saved cleaned df")

saved cleaned df

In [18]:
df_foodprices['date'] = pd.to_datetime(df_foodprices['date'])
print(df_foodprices[df_foodprices['commodity'] == 'Rice'][df_foodprices['date'].dt.year == 2024]['admin1'].unique())

IndexError: invalid index to scalar variable.